replicaCount: 1

kedaDeployment:
  enabled: false
  serviceName: keda-app
  labels: 
    app: keda-app
  kedaTrigger:
    type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local
      metricName: http_requests_total
      threshold: "100"
      query: sum(rate(http_requests_total[5m]))
  baseline:
    name: keda-app-baseline
    replicaCount: 1
    image:
      repository: httpd
      tag: "latest"
      pullPolicy: IfNotPresent
  canary:
    name: keda-app-canary
    replicaCount: 1
    image:
      repository: httpd
      tag: "latest"
      pullPolicy: IfNotPresent

hpaDeployment:
  enabled: true
  serviceName: hpa-app
  labels: 
    app: hpa-app
  baseline:
    name: keda-app-baseline
    replicaCount: 1
    image:
      repository: httpd
      tag: "latest"
      pullPolicy: IfNotPresent
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
  canary:
    name: keda-app-canary
    replicaCount: 1
    image:
      repository: httpd
      tag: "latest"
      pullPolicy: IfNotPresent
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
