replicaCount: 1
hpaDeployment:
  enabled: true
  serviceName: hpa-app
  labels: 
    app: hpa-app
    testing-hpa: now
  baseline:
    name: hpa-app-baseline
    replicaCount: 1
    image:
      repository: httpd
      tag: "latest"
      pullPolicy: IfNotPresent
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
  canary:
    name: hpa-app-canary
    replicaCount: 1
    image:
      repository: httpd
      tag: "latest"
      pullPolicy: IfNotPresent
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
