apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  labels:
    app: my-app
    environment: production
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"

  # JSON configuration stored as a ConfigMap key
  config.json: |-
    {
      "service": "my-service",
      "version": "1.0.0",
      "features": {
        "enabled": true
      }
    }
