apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  labels:
    app: test-app
data:
  environment: "staging"
  log_level: "debug"
  api_url: "https://api.example.com"
  feature_flag: "enabled"
