apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kedaDeployment.name }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.kedaDeployment.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hpaDeployment.name }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.hpaDeployment.name }}
